INSERT INTO Player ( player_name) VALUES ('Brijesh');
INSERT INTO Player ( player_name) VALUES ('Vimal');
INSERT INTO Player ( player_name) VALUES ('Prerana');
INSERT INTO Player ( player_name) VALUES ('Geeta');
INSERT INTO Player ( player_name) VALUES ('Denial');
INSERT INTO Player ( player_name) VALUES ('Tom');

INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (16,6);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (46,25);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (49,11);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (62,19);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (64,60);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (74,53);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (89,68);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (92,88);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (95,75);
INSERT INTO Snake (START_POSITION  ,END_POSITION  ) VALUES (99,80);


INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES (2,38);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES (7,14);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(8,31);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(15,26);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(21,42);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(36,44);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(51,67);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(71,91);
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(78,98)
INSERT INTO Ladder (START_POSITION  ,END_POSITION  ) VALUES(87,94)
